---
abstract: 'XML::Atom::Server for PSGI'
author:
  - 'Daisuke Maki <lestrrat+github@gmail.com>'
build_requires:
  LWP::Protocol::PSGI: 0
  Test::Fatal: 0.010
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Atom-Server-PSGI
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  XML::Atom::Server::PSGI:
    file: lib/XML/Atom/Server/PSGI.pm
    version: 0.03
requires:
  Digest::SHA1: 0
  MIME::Base64: 0
  Plack: 1.0024
  XML::Atom: 0.41
  perl: 5.008001
resources:
  bugtracker: https://github.com/lestrrat/p5-XML-Atom-Server-PSGI/issues
  homepage: https://github.com/lestrrat/p5-XML-Atom-Server-PSGI
  repository: git://github.com/lestrrat/p5-XML-Atom-Server-PSGI.git
version: 0.03
